---

- hosts: all
  become: false
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    become: yes

- hosts: all
  become: false
  tasks:
  
  - name: create simone user
    tags: always
    user: 
      name: simone
      groups: root
      
  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOZG4fHqhjVu9kEKQsaceEV6X2N8Ke+uEAWMiRmkven1 ansible"

  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

- hosts: workstations
  become: false
  tasks:
  
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.10.3/terraform_1.10.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    become: yes

- hosts: web_servers
  become: false
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache, apache2, centos
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: start apache (Ubtunu)
    tags: apache, apacheh2, ubuntu
    command: service apache2 start
    #service:
    #  name: apache2
    #  state: started
    #  enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: false
  tasks:

  - name: install mariadb package (CentOS)
    tags: db,mariadb,ubuntu
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,centos,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: false
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

