---

- hosts: all
  become: false
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    become: yes

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
