- hosts: all
  become: true
  tasks:
    - name: install apache2 package
      apt:
        name: apache2
        state: latest
        #update_cache: true

    - name: start apache service
      service:
        name: apache2
        state: started
        enabled: true
